# Generated by Django 3.2.7 on 2021-09-29 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionarios',
            name='departamento',
        ),
        migrations.AddField(
            model_name='funcionarios',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='empresas.empresas'),
        ),
    ]
