# Generated by Django 3.2.7 on 2021-09-29 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0002_alter_departamentos_empresa'),
        ('funcionarios', '0002_auto_20210929_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionarios',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='departamentos.departamentos'),
        ),
    ]
