# Generated by Django 3.2.7 on 2021-09-26 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=100, unique=True, verbose_name='Razao Social')),
                ('nome_fantasia', models.CharField(max_length=100, verbose_name='Nome Fantasia')),
                ('cnpj', models.CharField(max_length=15, unique=True, verbose_name='CNPJ')),
                ('endereco', models.CharField(max_length=200, verbose_name='Endereco')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telefone', models.CharField(max_length=14, verbose_name='Telefone')),
            ],
        ),
    ]
