# Generated by Django 3.2.7 on 2021-09-26 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        ('usuarios', '0002_usuarios_departamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='empresas.empresas'),
            preserve_default=False,
        ),
    ]
