# Generated by Django 3.2.7 on 2021-09-26 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_usuarios_empresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='empresa',
        ),
    ]
