# Generated by Django 3.2.7 on 2021-09-27 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_auto_20210926_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='telefone'),
        ),
    ]
