# Generated by Django 3.2.7 on 2021-09-27 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requerimentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('de', models.CharField(max_length=100, verbose_name='De')),
                ('para', models.CharField(max_length=100, verbose_name='Para')),
                ('assunto', models.CharField(max_length=100, verbose_name='Assunto')),
                ('conteudo', models.TextField(max_length=100, verbose_name='Conteudo')),
            ],
        ),
        migrations.DeleteModel(
            name='Documentos',
        ),
        migrations.DeleteModel(
            name='Tipo',
        ),
    ]
